### ISSUE TITLE
I cant swipe, using android

### ISSUE THREAD

**Issue by nuclearxstudios** [MorochoRochaDarwin/RNSwipeVerify#3]
**I can't touch the button nor slide it**

    constructor(props) {
        super(props)
        this.state = { isUnlocked: false, isUploaded: false }
    }

    render () {
        const { isUnlocked, isUploaded } = this.state

        return (
            <View style={{ marginTop: 20, paddingBottom: 20 }}>
                <RNSwipeVerify ref={ref => this.swipeVerify = ref}
                    buttonSize={60}
                    onVerified={() => {
                        this.setState({ isUnlocked: true })
                    }}
                >
                    <Text>{isUnlocked ? 'UNLOCKED' : 'slide to unlock'}</Text>
                </RNSwipeVerify>
            </View>
        );
    }

**Comment by darwin-morocho** [comment]
just define a height in the View, the height value must be the same of the buttonSize. Like this 
```JSX

const BUTTON_SIZE=60;
.
.
.

constructor(props) {
    super(props)
    this.state = { isUnlocked: false, isUploaded: false }
}

render () {
    const { isUnlocked, isUploaded } = this.state

    return (
        <View style={{ height:BUTTON_SIZE }}>
            <RNSwipeVerify ref={ref => this.swipeVerify = ref}
                buttonSize={BUTTON_SIZE}
                onVerified={() => {
                    this.setState({ isUnlocked: true })
                }}
            >
                <Text>{isUnlocked ? 'UNLOCKED' : 'slide to unlock'}</Text>
            </RNSwipeVerify>
        </View>
    );
}
```

**Comment by darwin-morocho** [comment]
if you don't want add the height, just update the package to 0.1.6

**Comment by nuclearxstudios** [comment]
> if you don't want add the height, just update the package to 0.1.6

Thanks alot
